import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Bell, Check, ChevronLeft, ChevronRight, Eye, RefreshCw, X } from 'lucide-react';
import { AppShell, PageIntro } from '@/components/app-shell';
import { InlineNotice, LoadingRows, Panel, PanelHeading, QueryState } from '@/components/console-ui';
import { useCapability } from '@/lib/session';
import { apiRequest } from '@/lib/api';

export type AlertRecord = { id: string; organization_id: string; organization_name?: string | null; device_id: string; device: { id: string; hostname: string; last_seen_at?: string | null }; type: string; severity: 'warning' | 'critical'; state: 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED'; resource: string | null; title: string; summary: string; opened_at: string; last_triggered_at: string; acknowledged_at: string | null; resolved_at: string | null; acknowledged_by: string | null; trigger_value: number | null; threshold_value: number | null; occurrence_count: number; events?: AlertEvent[] };
type AlertEvent = { id: string; event_type: string; previous_state: string | null; new_state: string | null; previous_severity: string | null; new_severity: string | null; actor: string | null; timestamp: string };
type AlertList = { items: AlertRecord[]; page: number; page_size: number; total: number };
const stateTabs = ['ACTIVE', 'ALL', 'OPEN', 'ACKNOWLEDGED', 'RESOLVED'] as const;

async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> { return apiRequest<T>(url.replace(/^\/api/, ''), init); }
export function relativeAge(timestamp: string) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(timestamp).getTime()) / 60000)); return minutes < 1 ? '<1m' : minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.floor(minutes / 60)}h` : `${Math.floor(minutes / 1440)}d`; }
export function alertTypeLabel(type: string) { return ({ DEVICE_OFFLINE: 'Device offline', CPU_HIGH: 'CPU sustained high', MEMORY_HIGH: 'Memory sustained high', DISK_HIGH: 'Disk usage high' } as Record<string, string>)[type] ?? type; }

export default function Alerts() {
  const client = useQueryClient();
  const canAcknowledge = useCapability('alert:acknowledge');
  const [state, setState] = useState<(typeof stateTabs)[number]>('ACTIVE');
  const [severity, setSeverity] = useState('');
  const [type, setType] = useState('');
  const [device, setDevice] = useState('');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<string>();
  const params = new URLSearchParams({ page: String(page), page_size: '25' });
  if (state === 'ACTIVE') params.set('active', 'true'); else if (state !== 'ALL') params.set('state', state);
  if (severity) params.set('severity', severity); if (type) params.set('type', type); if (device) params.set('device_id', device);
  const query = useQuery({ queryKey: ['alerts', state, severity, type, device, page], refetchInterval: 30000, queryFn: () => fetchJson<AlertList>(`/api/v1/alerts?${params}`) });
  const devices = useQuery({ queryKey: ['alert-device-options'], queryFn: () => fetchJson<{ items: Array<{ id: string; hostname: string }> }>('/api/v1/devices?page_size=100') });
  const detail = useQuery({ queryKey: ['alert-detail', selected], enabled: Boolean(selected), queryFn: () => fetchJson<AlertRecord>(`/api/v1/alerts/${selected}`) });
  const acknowledge = useMutation({ mutationFn: (id: string) => fetchJson(`/api/v1/alerts/${id}/acknowledge`, { method: 'POST' }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['alerts'] }), client.invalidateQueries({ queryKey: ['alert-detail'] }), client.invalidateQueries({ queryKey: ['dashboard-alerts'] })]); } });
  const setFilter = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const totalPages = Math.max(1, Math.ceil((query.data?.total ?? 0) / 25));
  return <AppShell><PageIntro eyebrow="Alert operations" title="Alerts" description="Deduplicated endpoint incidents requiring operator attention." action={<button type="button" onClick={() => void query.refetch()} className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-[11px] font-semibold"><RefreshCw size={14} className={query.isFetching ? 'animate-spin' : ''} />Refresh</button>} />
    <div className="mb-4 flex gap-1 overflow-x-auto border-b border-border">{stateTabs.map((item) => <button type="button" key={item} onClick={() => { setState(item); setPage(1); }} className={`border-b-2 px-3 py-2.5 text-[10px] font-bold ${state === item ? 'border-accent text-primary' : 'border-transparent text-muted-foreground'}`}>{item.charAt(0) + item.slice(1).toLowerCase()}</button>)}</div>
    <Panel><div className="grid gap-3 border-b border-border p-4 md:grid-cols-3"><select value={severity} onChange={(event) => setFilter(setSeverity, event.target.value)} className="field-control"><option value="">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option></select><select value={type} onChange={(event) => setFilter(setType, event.target.value)} className="field-control"><option value="">All alert types</option><option value="DEVICE_OFFLINE">Device offline</option><option value="CPU_HIGH">CPU high</option><option value="MEMORY_HIGH">Memory high</option><option value="DISK_HIGH">Disk high</option></select><select value={device} onChange={(event) => setFilter(setDevice, event.target.value)} className="field-control"><option value="">All devices</option>{devices.data?.items.map((item) => <option value={item.id} key={item.id}>{item.hostname}</option>)}</select></div>
      {query.isLoading ? <LoadingRows count={7} /> : query.isError ? <QueryState kind="error" onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <div className="flex min-h-56 flex-col items-center justify-center text-center"><Bell size={25} className="mb-3 text-muted-foreground/50" /><p className="text-[13px] font-semibold text-primary">{state === 'ACTIVE' ? 'No active alerts' : 'No alerts match these filters'}</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1080px]"><thead><tr className="bg-muted/45 text-left text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground"><th className="px-4 py-3">Severity</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Alert</th><th className="px-4 py-3">Device</th><th className="px-4 py-3">Resource</th><th className="px-4 py-3">Trigger</th><th className="px-4 py-3">Opened</th><th className="px-4 py-3">Triggered</th><th className="px-4 py-3">Count</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-border/60">{query.data.items.map((alert) => <tr key={alert.id} className="hover:bg-muted/40"><td className="px-4 py-3"><AlertPill value={alert.severity} /></td><td className="px-4 py-3"><AlertPill value={alert.state} /></td><td className="px-4 py-3"><p className="text-[11px] font-semibold text-primary">{alertTypeLabel(alert.type)}</p><p className="mt-0.5 max-w-[230px] truncate text-[10px] text-muted-foreground">{alert.summary}</p></td><td className="px-4 py-3"><Link href={`/devices/${alert.device_id}`} className="text-[11px] font-semibold text-[#b57504]">{alert.device.hostname}</Link></td><td className="px-4 py-3 font-mono-data text-[10px]">{alert.resource ?? 'Device'}</td><td className="px-4 py-3 font-mono-data text-[10px]">{alert.trigger_value == null ? 'Status' : `${alert.trigger_value.toFixed(1)}% / ${alert.threshold_value?.toFixed(0)}%`}</td><td className="px-4 py-3 font-mono-data text-[10px]" title={new Date(alert.opened_at).toLocaleString()}>{relativeAge(alert.opened_at)}</td><td className="px-4 py-3 font-mono-data text-[10px]" title={new Date(alert.last_triggered_at).toLocaleString()}>{relativeAge(alert.last_triggered_at)}</td><td className="px-4 py-3 font-mono-data text-[10px]">{alert.occurrence_count}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button type="button" onClick={() => setSelected(alert.id)} className="rounded border p-1.5" aria-label="View alert"><Eye size={14} /></button>{alert.state === 'OPEN' && <button type="button" disabled={!canAcknowledge || acknowledge.isPending} onClick={() => acknowledge.mutate(alert.id)} className="rounded border p-1.5 text-[#14704f] disabled:opacity-35" aria-label="Acknowledge alert"><Check size={14} /></button>}</div></td></tr>)}</tbody></table></div>}
      <div className="flex items-center justify-between border-t border-border px-4 py-3 text-[10px] text-muted-foreground"><span>{query.data?.total ?? 0} alerts</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border p-1 disabled:opacity-30"><ChevronLeft size={14} /></button><span>{page} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="rounded border p-1 disabled:opacity-30"><ChevronRight size={14} /></button></div></div>
    </Panel>{acknowledge.isError && <div className="mt-4"><InlineNotice tone="red">Acknowledgement failed. Verify the administrative token and alert state.</InlineNotice></div>}
    {selected && <AlertDrawer alert={detail.data} loading={detail.isLoading} onClose={() => setSelected(undefined)} onAcknowledge={detail.data?.state === 'OPEN' && canAcknowledge ? () => acknowledge.mutate(detail.data!.id) : undefined} />}
  </AppShell>;
}

export function AlertPill({ value }: { value: string }) { const normalized = value.toUpperCase(); const style = normalized === 'CRITICAL' || normalized === 'OPEN' ? 'bg-[#fce4df] text-[#ae3e32]' : normalized === 'WARNING' ? 'bg-[#fff0cc] text-[#986306]' : normalized === 'ACKNOWLEDGED' ? 'bg-[#e8eef5] text-[#38536b]' : 'bg-[#d9f5e8] text-[#14704f]'; return <span className={`inline-flex rounded-full px-2 py-1 text-[9px] font-bold uppercase ${style}`}>{value}</span>; }
function AlertDrawer({ alert, loading, onClose, onAcknowledge }: { alert?: AlertRecord; loading: boolean; onClose: () => void; onAcknowledge?: () => void }) { return <><button type="button" className="fixed inset-0 z-40 bg-[#07121b]/45" aria-label="Close alert detail" onClick={onClose} /><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto border-l border-border bg-background shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-background px-5 py-4"><h2 className="text-[14px] font-semibold">Alert detail</h2><button onClick={onClose} className="rounded p-2" aria-label="Close"><X size={17} /></button></div>{loading || !alert ? <LoadingRows count={6} /> : <div className="space-y-5 p-5"><div><div className="mb-3 flex gap-2"><AlertPill value={alert.severity} /><AlertPill value={alert.state} /></div><h3 className="text-xl font-semibold text-primary">{alert.title}</h3><p className="mt-2 text-[12px] leading-5 text-muted-foreground">{alert.summary}</p></div><dl className="grid grid-cols-2 gap-px overflow-hidden rounded-md border bg-border text-[11px]">{[['Device', alert.device.hostname], ['Resource', alert.resource ?? 'Device'], ['Trigger', alert.trigger_value == null ? 'Status transition' : `${alert.trigger_value.toFixed(1)}%`], ['Threshold', alert.threshold_value == null ? 'Offline' : `${alert.threshold_value.toFixed(1)}%`], ['Opened', new Date(alert.opened_at).toLocaleString()], ['Last triggered', new Date(alert.last_triggered_at).toLocaleString()], ['Occurrences', String(alert.occurrence_count)], ['Acknowledged by', alert.acknowledged_by ?? 'Not acknowledged']].map(([key, value]) => <div className="bg-card p-3" key={key}><dt className="text-muted-foreground">{key}</dt><dd className="mt-1 font-semibold text-primary">{value}</dd></div>)}</dl>{onAcknowledge && <button onClick={onAcknowledge} className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-[11px] font-bold text-primary-foreground"><Check size={14} />Acknowledge</button>}<Panel><PanelHeading eyebrow="Lifecycle" title="Timeline" />{alert.events?.length ? <div className="divide-y divide-border">{alert.events.map((event) => <div key={event.id} className="flex gap-3 px-4 py-3"><span className="mt-1 h-2 w-2 rounded-full bg-accent" /><div><p className="text-[11px] font-semibold">{event.event_type.replaceAll('_', ' ')}</p><time className="text-[10px] text-muted-foreground">{new Date(event.timestamp).toLocaleString()}</time></div></div>)}</div> : <div className="p-4 text-[11px] text-muted-foreground">No lifecycle events recorded.</div>}</Panel></div>}</aside></>; }
