import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Boxes, ChevronLeft, ChevronRight, Monitor, Search } from 'lucide-react';
import { AppShell, PageIntro } from '@/components/app-shell';
import { InlineNotice, LoadingRows, Panel, PanelHeading, QueryState, StatusPill } from '@/components/console-ui';
import { adminFetch } from '@/lib/admin-api';

type VersionCount = { version: string | null; endpoints: number };
type FleetApp = { software_identity: string; name: string; publisher: string | null; architecture: string; installed_endpoints: number; latest_observed: string; versions: VersionCount[] };
type SoftwareDevice = { device_id: string; hostname: string; agent_id: string; status: string; version: string | null; architecture: string; last_seen_at: string };
type Page<T> = { items: T[]; page: number; page_size: number; total: number };

export default function Software() {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState<FleetApp>();
  const query = useQuery({ queryKey: ['fleet-software', search, page], queryFn: () => adminFetch<Page<FleetApp>>(`/software?page=${page}&page_size=25&search=${encodeURIComponent(search)}`) });
  const devices = useQuery({ queryKey: ['software-devices', selected?.software_identity], enabled: Boolean(selected), queryFn: () => adminFetch<Page<SoftwareDevice>>(`/software/${selected!.software_identity}/devices?page_size=100`) });
  return <AppShell><PageIntro eyebrow="Fleet inventory" title="Software" description="Installed applications and version distribution reported by managed endpoints." action={<div className="flex items-center gap-2 text-[11px] text-muted-foreground"><Boxes size={15} />{query.data?.total ?? 0} applications</div>} />
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.85fr]">
      <Panel><PanelHeading eyebrow="Application catalog" title="Installed software" meta="Grouped by normalized identity and architecture" />
        <div className="border-b border-border p-4"><label className="relative block"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={15} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="field-control pl-9" placeholder="Search application or publisher" /></label></div>
        {query.isLoading ? <LoadingRows count={8} /> : query.isError ? <div className="p-5"><InlineNotice tone="red">{query.error.message}</InlineNotice></div> : !query.data?.items.length ? <QueryState kind="empty" /> : <div className="overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="bg-muted/45 text-left text-[9px] font-bold uppercase text-muted-foreground"><th className="px-5 py-3">Application</th><th className="px-4 py-3">Publisher</th><th className="px-4 py-3">Versions</th><th className="px-4 py-3">Endpoints</th><th className="px-4 py-3">Latest observed</th></tr></thead><tbody className="divide-y divide-border/60">{query.data.items.map((item) => <tr key={item.software_identity} onClick={() => setSelected(item)} className={`cursor-pointer hover:bg-muted/40 ${selected?.software_identity === item.software_identity ? 'bg-muted/60' : ''}`}><td className="px-5 py-4"><p className="text-[12px] font-semibold text-primary">{item.name}</p><p className="mt-1 text-[9px] uppercase text-muted-foreground">{item.architecture}</p></td><td className="px-4 py-4 text-[11px] text-muted-foreground">{item.publisher || 'Unknown'}</td><td className="px-4 py-4 text-[10px] text-primary">{item.versions.slice(0, 3).map((version) => version.version || 'Unknown').join(', ')}</td><td className="px-4 py-4 font-mono-data text-[12px] font-bold text-primary">{item.installed_endpoints}</td><td className="px-4 py-4 text-[10px] text-muted-foreground">{new Date(item.latest_observed).toLocaleString()}</td></tr>)}</tbody></table></div>}
        <Pager page={page} total={query.data?.total ?? 0} size={25} setPage={setPage} />
      </Panel>
      <Panel><PanelHeading eyebrow="Version distribution" title={selected?.name ?? 'Select an application'} meta={selected?.publisher ?? 'Endpoint coverage appears here'} />
        {!selected ? <div className="flex min-h-64 items-center justify-center text-[11px] text-muted-foreground">Select an application from the catalog</div> : <><div className="divide-y divide-border/60">{selected.versions.map((version) => <div key={version.version ?? 'unknown'} className="flex items-center justify-between px-5 py-4"><span className="font-mono-data text-[11px] text-primary">{version.version || 'Unknown version'}</span><span className="text-[11px] font-bold text-primary">{version.endpoints} endpoints</span></div>)}</div><div className="border-t border-border"><PanelHeading eyebrow="Installed endpoints" title="Devices" />{devices.isLoading ? <LoadingRows count={4} /> : devices.data?.items.map((device) => <Link key={device.device_id} href={`/devices/${device.device_id}`} className="flex items-center gap-3 border-t border-border/60 px-5 py-4 hover:bg-muted/40"><Monitor size={15} className="text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold text-primary">{device.hostname}</p><p className="mt-1 font-mono-data text-[9px] text-muted-foreground">{device.version || 'Unknown'} · {device.architecture}</p></div><StatusPill status={device.status as 'ONLINE' | 'OFFLINE' | 'UNKNOWN'} /></Link>)}</div></>}
      </Panel>
    </div>
  </AppShell>;
}

function Pager({ page, total, size, setPage }: { page: number; total: number; size: number; setPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / size)); return <div className="flex items-center justify-between border-t border-border px-5 py-3 text-[10px] text-muted-foreground"><span>Page {page} of {pages}</span><div className="flex gap-1"><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border p-2 disabled:opacity-30"><ChevronLeft size={13} /></button><button aria-label="Next page" disabled={page >= pages} onClick={() => setPage(page + 1)} className="rounded border p-2 disabled:opacity-30"><ChevronRight size={13} /></button></div></div>; }

export type DeviceSoftwareRecord = { id: string; software_identity: string; name: string; version: string | null; publisher: string | null; architecture: string; install_date: string | null; first_seen_at: string; last_seen_at: string; is_present: boolean; removed_at: string | null; system_component: boolean };
type SoftwareChange = { id: string; change_type: string; name: string; previous_version: string | null; current_version: string | null; observed_at: string };

export function DeviceSoftware({ deviceId }: { deviceId: string }) {
  const [search, setSearch] = useState(''); const [architecture, setArchitecture] = useState(''); const [present, setPresent] = useState('true'); const [sort, setSort] = useState('name');
  const params = new URLSearchParams({ page: '1', page_size: '100', search, present, sort }); if (architecture) params.set('architecture', architecture);
  const inventory = useQuery({ queryKey: ['device-software', deviceId, search, architecture, present, sort], queryFn: () => adminFetch<Page<DeviceSoftwareRecord>>(`/devices/${deviceId}/software?${params}`) });
  const changes = useQuery({ queryKey: ['device-software-changes', deviceId], queryFn: () => adminFetch<Page<SoftwareChange>>(`/devices/${deviceId}/software/changes?page_size=25`) });
  return <div className="space-y-5"><Panel><PanelHeading eyebrow="Software inventory" title="Applications" meta={`${inventory.data?.total ?? 0} matching records`} /><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_150px_150px_150px]"><input className="field-control" placeholder="Search application or publisher" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="field-control" value={architecture} onChange={(event) => setArchitecture(event.target.value)}><option value="">All architectures</option><option value="x64">x64</option><option value="x86">x86</option><option value="unknown">Unknown</option></select><select className="field-control" value={present} onChange={(event) => setPresent(event.target.value)}><option value="true">Present</option><option value="false">Removed</option><option value="all">All records</option></select><select className="field-control" value={sort} onChange={(event) => setSort(event.target.value)}><option value="name">Application</option><option value="version">Version</option><option value="publisher">Publisher</option><option value="first_seen">First seen</option><option value="last_seen">Last seen</option></select></div>{inventory.isLoading ? <LoadingRows count={7} /> : inventory.isError ? <div className="p-5"><InlineNotice tone="red">{inventory.error.message}</InlineNotice></div> : !inventory.data?.items.length ? <QueryState kind="empty" /> : <div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="bg-muted/45 text-left text-[9px] font-bold uppercase text-muted-foreground"><th className="px-5 py-3">Application</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Publisher</th><th className="px-4 py-3">Architecture</th><th className="px-4 py-3">Install date</th><th className="px-4 py-3">First seen</th><th className="px-4 py-3">Last seen</th></tr></thead><tbody className="divide-y divide-border/60">{inventory.data.items.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="text-[12px] font-semibold text-primary">{item.name}</p>{item.system_component && <span className="text-[9px] text-muted-foreground">System component</span>}</td><td className="px-4 py-4 font-mono-data text-[10px]">{item.version || '—'}</td><td className="px-4 py-4 text-[10px] text-muted-foreground">{item.publisher || 'Unknown'}</td><td className="px-4 py-4 text-[10px] uppercase">{item.architecture}</td><td className="px-4 py-4 text-[10px] text-muted-foreground">{date(item.install_date)}</td><td className="px-4 py-4 text-[10px] text-muted-foreground">{date(item.first_seen_at)}</td><td className="px-4 py-4 text-[10px] text-muted-foreground">{date(item.last_seen_at)}</td></tr>)}</tbody></table></div>}</Panel>
    <Panel><PanelHeading eyebrow="Change tracking" title="Software changes" meta="Observed changes from complete snapshots" />{changes.isLoading ? <LoadingRows count={5} /> : !changes.data?.items.length ? <QueryState kind="empty" /> : <div className="divide-y divide-border/60">{changes.data.items.map((change) => <div key={change.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[160px_130px_1fr_1fr]"><time className="text-[10px] text-muted-foreground">{date(change.observed_at)}</time><span className={`text-[9px] font-bold ${change.change_type === 'REMOVED' ? 'text-destructive' : change.change_type === 'INSTALLED' ? 'text-[#14704f]' : 'text-[#a56a00]'}`}>{change.change_type.replace('_', ' ')}</span><span className="text-[11px] font-semibold text-primary">{change.name}</span><span className="font-mono-data text-[10px] text-muted-foreground">{change.previous_version || '—'} → {change.current_version || '—'}</span></div>)}</div>}</Panel></div>;
}
function date(value: string | null) { return value ? new Date(value).toLocaleString() : '—'; }
