import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { devicesTable, privilegedActionsTable } from "./nexora";
import { organizationsTable, usersTable } from "./tenancy";

export const remoteCommandStatusEnum = pgEnum("remote_command_status", ["PENDING", "READY", "CLAIMED", "RUNNING", "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCEL_REQUESTED", "CANCELLED", "EXPIRED", "UNKNOWN"]);
export const remoteCommandShellEnum = pgEnum("remote_command_shell", ["CMD", "POWERSHELL"]);
export const remoteCommandJobsTable = pgTable("nexora_remote_command_jobs", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizationsTable.id), deviceId: uuid("device_id").notNull().references(() => devicesTable.id), privilegedActionId: uuid("privileged_action_id").notNull().unique().references(() => privilegedActionsTable.id),
  status: remoteCommandStatusEnum("status").notNull().default("PENDING"), shellType: remoteCommandShellEnum("shell_type").notNull(), commandPayload: jsonb("command_payload").notNull(), workingDirectory: text("working_directory"), timeoutSeconds: integer("timeout_seconds").notNull().default(60), requestedByUserId: uuid("requested_by_user_id").notNull().references(() => usersTable.id), approvedByUserId: uuid("approved_by_user_id").references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), readyAt: timestamp("ready_at", { withTimezone: true }), claimedAt: timestamp("claimed_at", { withTimezone: true }), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }), lastExecutionHeartbeatAt: timestamp("last_execution_heartbeat_at", { withTimezone: true }), executionId: uuid("execution_id"), executionCapabilityHash: text("execution_capability_hash"), executionAttempt: integer("execution_attempt").notNull().default(0), exitCode: integer("exit_code"), stdout: text("stdout"), stderr: text("stderr"), stdoutTruncated: boolean("stdout_truncated").notNull().default(false), stderrTruncated: boolean("stderr_truncated").notNull().default(false), failureCode: text("failure_code"), failureMessage: text("failure_message"), cancelRequestedAt: timestamp("cancel_requested_at", { withTimezone: true }), createdRequestId: text("created_request_id"), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("nexora_remote_commands_org_idx").on(t.organizationId), index("nexora_remote_commands_device_idx").on(t.deviceId), index("nexora_remote_commands_status_idx").on(t.status), index("nexora_remote_commands_created_idx").on(t.createdAt), index("nexora_remote_commands_expiry_idx").on(t.expiresAt), index("nexora_remote_commands_lease_idx").on(t.leaseExpiresAt), uniqueIndex("nexora_remote_commands_action_unique").on(t.privilegedActionId)]);
